### ISSUE TITLE
maintainer?

### ISSUE THREAD

**Issue by chrisdrackett** [malte-wessel/react-textfit#11]
@malte-wessel curious what your plans for this package are. I see in the last couple days there has been some activity resulting in pull requests. However, I also see that the project hasn't been updated in quite a while.

I'm also thinking about starting to use the project, but based on the current state think I'll probably be making my own fork so I can pull in fixes from others as well as make my own. Hopefully there is a way to get all these fixes from the community into a canonical repository.

**Comment by malte-wessel** [comment]
hey @chrisdrackett I'm currently too busy to take care of this project. I would appreciate If anyone could take over.

**Comment by tbroadley** [comment]
@malte-wessel I would be happy to maintain this project. If you're interested, please let me know what the steps for that look like :smile:

**Comment by chrisdrackett** [comment]
@tbroadley / @malte-wessel I'd also be happy to help out (not sure if I want to be the only maintainer). I may or may not think of the API/base features in a completely different way, which is worth taking into consideration :)

**Comment by tbroadley** [comment]
@malte-wessel Any thoughts about this?

**Comment by malte-wessel** [comment]
I'm open for PRs, but I don't want to change the existing API (for now). Because people are already using the lib

**Comment by tbroadley** [comment]
@malte-wessel That's reasonable. Major API changes could be released as a new major version, which would allow people to stick with the current API if they wanted to.

Would you be able to at least take a look at https://github.com/malte-wessel/react-textfit/pull/9 and https://github.com/malte-wessel/react-textfit/pull/10? Those two PRs fix bugs that are causing console errors.

**Comment by tbroadley** [comment]
Much appreciated @malte-wessel :) Any chance you could publish a new version to NPM with these fixes?

**Comment by malte-wessel** [comment]
I'm on it :)

**Comment by malte-wessel** [comment]
published!

**Comment by tbroadley** [comment]
Thank you so much! 😄

**Comment by NoMemoryError** [comment]
@malte-wessel great. Finally the much needed prs are merged. I will now update my projects `package.json` as well.

**Comment by denis-sokolov** [comment]
In addition to **malte-wessel**, I am also available to merge features in, so feel more motivated creating them! :-)
