### ISSUE TITLE
Consider using vw as underlying font unit

### ISSUE THREAD

**Issue by ForbesLindesay** [malte-wessel/react-textfit#14]
`vw` lets you specify font-size as a proportion of view width.  I suspect that often the font-size will change roughly in proportion to the view width as you resize the browser.  If this library used `vw` instead of `px`, it might smooth out the transitions by making it relatively rare that the font-size needed to change significantly.  There would still need to be a way to select `px` for when the library is used in fixed-width layouts.

**Comment by denis-sokolov** [comment]
This is a good suggestion. If anyone is up to implement it, I would be open to accept a PR.

We try to keep the outstanding issues under control, so I will be closing this, as until someone implements this, there is no action to be done.
