### ISSUE TITLE
May not include paddings (work in demo)

### ISSUE THREAD

**Issue by StipJey** [malte-wessel/react-textfit#22]
![image](https://cloud.githubusercontent.com/assets/8746529/26486475/f6ba7802-4203-11e7-87a0-278c158ec88b.png)

**Comment by StipJey** [comment]
not fixed

**Comment by denis-sokolov** [comment]
Thanks for bringing this up. Apparently we did not update the website in a while. Now I did!

The problem described is now nearly fixed, it only shows up on very small font sizes. Would be nice to fix it entirely, but it is small enough to not warrant the issue open. A PR would be welcome, though.
