### ISSUE TITLE
Having different resize for the same text

### ISSUE THREAD

**Issue by MarcMagnin** [malte-wessel/react-textfit#28]
On the following picture is it possible to have a part of a text resize with another factor? (having the "ms" text smaller)
![image](https://user-images.githubusercontent.com/725667/28917722-e2fe829e-7846-11e7-82fc-79a8d6e7b105.png)
Many thanks

**Comment by denis-sokolov** [comment]
You can do this today! We manipulate the font size using the CSS `font-size` at the top level container. You need to add a wrapper element with `font-size` using percents:

```jsx
<Textfit>
  1<span style={{ fontSize: '80%' }}>ms</span>
</Textfit>
```

**Comment by MarcMagnin** [comment]
marvellous!
