### ISSUE TITLE
Does it work with Next.js

### ISSUE THREAD

**Issue by avalero** [malte-wessel/react-textfit#85]
I am trying to use this with Next.js without success. I've thought it might be related to server-side rendering. Could you confirm if if can work on Next?

Thanks!

**Comment by V3RON** [comment]
You should be able to use it using Next's `dynamic` and importing Textfit on the client side only.

```
const Textfit = dynamic(
  () => import('react-textfit').then(mod =>  Textfit,
  { ssr: false }
)
```

Let me know if that works for you.

**Comment by avalero** [comment]
I works like charm. Thank you very much for your answer!!
